export const architectLiConstants = {
  GET_ARCHITECT_LI_REQUEST: "GET_ARCHITECT_LI_REQUEST",
  GET_ARCHITECT_LI_SUCCESS: "GET_ARCHITECT_LI_SUCCESS",
  GET_ARCHITECT_LI_FAILURE: "GET_ARCHITECT_LI_FAILURE",

  ADD_ARCHITECT_LI_REQUEST: "ADD_ARCHITECT_LI_REQUEST",
  ADD_ARCHITECT_LI_SUCCESS: "ADD_ARCHITECT_LI_SUCCESS",
  ADD_ARCHITECT_LI_FAILURE: "ADD_ARCHITECT_LI_FAILURE",

  UPDATE_ARCHITECT_LI_REQUEST: "UPDATE_ARCHITECT_LI_REQUEST",
  UPDATE_ARCHITECT_LI_SUCCESS: "UPDATE_ARCHITECT_LI_SUCCESS",
  UPDATE_ARCHITECT_LI_FAILURE: "UPDATE_ARCHITECT_LI_FAILURE",

  DELETE_ARCHITECT_LI_REQUEST: "DELETE_ARCHITECT_LI_REQUEST",
  DELETE_ARCHITECT_LI_SUCCESS: "DELETE_ARCHITECT_LI_SUCCESS",
  DELETE_ARCHITECT_LI_FAILURE: "DELETE_ARCHITECT_LI_FAILURE",
}
export const architectSkillsConstants = {
  GET_ARCHITECT_SKILLS_REQUEST: "GET_ARCHITECT_SKILLS_REQUEST",
  GET_ARCHITECT_SKILLS_SUCCESS: "GET_ARCHITECT_SKILLS_SUCCESS",
  GET_ARCHITECT_SKILLS_FAILURE: "GET_ARCHITECT_SKILLS_FAILURE",

  ADD_ARCHITECT_SKILLS_REQUEST: "ADD_ARCHITECT_SKILLS_REQUEST",
  ADD_ARCHITECT_SKILLS_SUCCESS: "ADD_ARCHITECT_SKILLS_SUCCESS",
  ADD_ARCHITECT_SKILLS_FAILURE: "ADD_ARCHITECT_SKILLS_FAILURE",

  UPDATE_ARCHITECT_SKILLS_REQUEST: "UPDATE_ARCHITECT_SKILLS_REQUEST",
  UPDATE_ARCHITECT_SKILLS_SUCCESS: "UPDATE_ARCHITECT_SKILLS_SUCCESS",
  UPDATE_ARCHITECT_SKILLS_FAILURE: "UPDATE_ARCHITECT_SKILLS_FAILURE",

  DELETE_ARCHITECT_SKILLS_REQUEST: "DELETE_ARCHITECT_SKILLS_REQUEST",
  DELETE_ARCHITECT_SKILLS_SUCCESS: "DELETE_ARCHITECT_SKILLS_SUCCESS",
  DELETE_ARCHITECT_SKILLS_FAILURE: "DELETE_ARCHITECT_SKILLS_FAILURE",
}

export const architectConstants = {
  GET_ARCHITECT_REQUEST: "GET_ARCHITECT_REQUEST",
  GET_ARCHITECT_SUCCESS: "GET_ARCHITECT_SUCCESS",
  GET_ARCHITECT_FAILURE: "GET_ARCHITECT_FAILURE",

  ADD_ARCHITECT_REQUEST: "ADD_ARCHITECT_REQUEST",
  ADD_ARCHITECT_SUCCESS: "ADD_ARCHITECT_SUCCESS",
  ADD_ARCHITECT_FAILURE: "ADD_ARCHITECT_FAILURE",

  UPDATE_ARCHITECT_REQUEST: "UPDATE_ARCHITECT_REQUEST",
  UPDATE_ARCHITECT_SUCCESS: "UPDATE_ARCHITECT_SUCCESS",
  UPDATE_ARCHITECT_FAILURE: "UPDATE_ARCHITECT_FAILURE",

  DELETE_ARCHITECT_REQUEST: "DELETE_ARCHITECT_REQUEST",
  DELETE_ARCHITECT_SUCCESS: "DELETE_ARCHITECT_SUCCESS",
  DELETE_ARCHITECT_FAILURE: "DELETE_ARCHITECT_FAILURE",
}

export const graniteTilesConstants = {
  GET_GRANITE_TILES_REQUEST: "GET_GRANITE_TILES_REQUEST",
  GET_GRANITE_TILES_SUCCESS: "GET_GRANITE_TILES_SUCCESS",
  GET_GRANITE_TILES_FAILURE: "GET_GRANITE_TILES_FAILURE",

  ADD_GRANITE_TILES_REQUEST: "ADD_GRANITE_TILES_REQUEST",
  ADD_GRANITE_TILES_SUCCESS: "ADD_GRANITE_TILES_SUCCESS",
  ADD_GRANITE_TILES_FAILURE: "ADD_GRANITE_TILES_FAILURE",

  UPDATE_GRANITE_TILES_REQUEST: "UPDATE_GRANITE_TILES_REQUEST",
  UPDATE_GRANITE_TILES_SUCCESS: "UPDATE_GRANITE_TILES_SUCCESS",
  UPDATE_GRANITE_TILES_FAILURE: "UPDATE_GRANITE_TILES_FAILURE",

  DELETE_GRANITE_TILES_REQUEST: "DELETE_GRANITE_TILES_REQUEST",
  DELETE_GRANITE_TILES_SUCCESS: "DELETE_GRANITE_TILES_SUCCESS",
  DELETE_GRANITE_TILES_FAILURE: "DELETE_GRANITE_TILES_FAILURE",
  SET_VIEW: "SET_VIEW"
}
export const benefitsConstants = {
  GET_BENEFITS_REQUEST: "GET_BENEFITS_REQUEST",
  GET_BENEFITS_SUCCESS: "GET_BENEFITS_SUCCESS",
  GET_BENEFITS_FAILURE: "GET_BENEFITS_FAILURE",

  ADD_BENEFITS_REQUEST: "ADD_BENEFITS_REQUEST",
  ADD_BENEFITS_SUCCESS: "ADD_BENEFITS_SUCCESS",
  ADD_BENEFITS_FAILURE: "ADD_BENEFITS_FAILURE",

  UPDATE_BENEFITS_REQUEST: "UPDATE_BENEFITS_REQUEST",
  UPDATE_BENEFITS_SUCCESS: "UPDATE_BENEFITS_SUCCESS",
  UPDATE_BENEFITS_FAILURE: "UPDATE_BENEFITS_FAILURE",

  DELETE_BENEFITS_REQUEST: "DELETE_BENEFITS_REQUEST",
  DELETE_BENEFITS_SUCCESS: "DELETE_BENEFITS_SUCCESS",
  DELETE_BENEFITS_FAILURE: "DELETE_BENEFITS_FAILURE",
  SET_VIEW: "SET_VIEW"
}
export const aboutUsConstants = {
  GET_ABOUT_US_REQUEST: "GET_ABOUT_US_REQUEST",
  GET_ABOUT_US_SUCCESS: "GET_ABOUT_US_SUCCESS",
  GET_ABOUT_US_FAILURE: "GET_ABOUT_US_FAILURE",

  ADD_ABOUT_US_REQUEST: "ADD_ABOUT_US_REQUEST",
  ADD_ABOUT_US_SUCCESS: "ADD_ABOUT_US_SUCCESS",
  ADD_ABOUT_US_FAILURE: "ADD_ABOUT_US_FAILURE",

  UPDATE_ABOUT_US_REQUEST: "UPDATE_ABOUT_US_REQUEST",
  UPDATE_ABOUT_US_SUCCESS: "UPDATE_ABOUT_US_SUCCESS",
  UPDATE_ABOUT_US_FAILURE: "UPDATE_ABOUT_US_FAILURE",

  DELETE_ABOUT_US_REQUEST: "DELETE_ABOUT_US_REQUEST",
  DELETE_ABOUT_US_SUCCESS: "DELETE_ABOUT_US_SUCCESS",
  DELETE_ABOUT_US_FAILURE: "DELETE_ABOUT_US_FAILURE",
}
export const paymentListConstants = {
  GET_PAYMENT_LIST_REQUEST: "GET_PAYMENT_LIST_REQUEST",
  GET_PAYMENT_LIST_SUCCESS: "GET_PAYMENT_LIST_SUCCESS",
  GET_PAYMENT_LIST_FAILURE: "GET_PAYMENT_LIST_FAILURE",

  ADD_PAYMENT_LIST_REQUEST: "ADD_PAYMENT_LIST_REQUEST",
  ADD_PAYMENT_LIST_SUCCESS: "ADD_PAYMENT_LIST_SUCCESS",
  ADD_PAYMENT_LIST_FAILURE: "ADD_PAYMENT_LIST_FAILURE",

  UPDATE_PAYMENT_LIST_REQUEST: "UPDATE_PAYMENT_LIST_REQUEST",
  UPDATE_PAYMENT_LIST_SUCCESS: "UPDATE_PAYMENT_LIST_SUCCESS",
  UPDATE_PAYMENT_LIST_FAILURE: "UPDATE_PAYMENT_LIST_FAILURE",

  DELETE_PAYMENT_LIST_REQUEST: "DELETE_PAYMENT_LIST_REQUEST",
  DELETE_PAYMENT_LIST_SUCCESS: "DELETE_PAYMENT_LIST_SUCCESS",
  DELETE_PAYMENT_LIST_FAILURE: "DELETE_PAYMENT_LIST_FAILURE",
  SET_VIEW: "SET_VIEW"
}
export const deliveryInfoConstants = {
  GET_DELIVERY_INFO_REQUEST: "GET_DELIVERY_INFO_REQUEST",
  GET_DELIVERY_INFO_SUCCESS: "GET_DELIVERY_INFO_SUCCESS",
  GET_DELIVERY_INFO_FAILURE: "GET_DELIVERY_INFO_FAILURE",

  ADD_DELIVERY_INFO_REQUEST: "ADD_DELIVERY_INFO_REQUEST",
  ADD_DELIVERY_INFO_SUCCESS: "ADD_DELIVERY_INFO_SUCCESS",
  ADD_DELIVERY_INFO_FAILURE: "ADD_DELIVERY_INFO_FAILURE",

  UPDATE_DELIVERY_INFO_REQUEST: "UPDATE_DELIVERY_INFO_REQUEST",
  UPDATE_DELIVERY_INFO_SUCCESS: "UPDATE_DELIVERY_INFO_SUCCESS",
  UPDATE_DELIVERY_INFO_FAILURE: "UPDATE_DELIVERY_INFO_FAILURE",

  DELETE_DELIVERY_INFO_REQUEST: "DELETE_DELIVERY_INFO_REQUEST",
  DELETE_DELIVERY_INFO_SUCCESS: "DELETE_DELIVERY_INFO_SUCCESS",
  DELETE_DELIVERY_INFO_FAILURE: "DELETE_DELIVERY_INFO_FAILURE",

}

export const engravingLayoutConstants = {
  GET_ENGRAVING_LAYOUT_REQUEST: "GET_ENGRAVING_LAYOUT_REQUEST",
  GET_ENGRAVING_LAYOUT_SUCCESS: "GET_ENGRAVING_LAYOUT_SUCCESS",
  GET_ENGRAVING_LAYOUT_FAILURE: "GET_ENGRAVING_LAYOUT_FAILURE",

  GET_ENGRAVING_LAYOUT_BY_SLUG_REQUEST: "GET_ENGRAVING_LAYOUT_BY_SLUG_REQUEST",
  GET_ENGRAVING_LAYOUT_BY_SLUG_SUCCESS: "GET_ENGRAVING_LAYOUT_BY_SLUG_SUCCESS",
  GET_ENGRAVING_LAYOUT_BY_SLUG_FAILURE: "GET_ENGRAVING_LAYOUT_BY_SLUG_FAILURE",

  ADD_ENGRAVING_LAYOUT_REQUEST: "ADD_ENGRAVING_LAYOUT_REQUEST",
  ADD_ENGRAVING_LAYOUT_SUCCESS: "ADD_ENGRAVING_LAYOUT_SUCCESS",
  ADD_ENGRAVING_LAYOUT_FAILURE: "ADD_ENGRAVING_LAYOUT_FAILURE",

  UPDATE_ENGRAVING_LAYOUT_REQUEST: "UPDATE_ENGRAVING_LAYOUT_REQUEST",
  UPDATE_ENGRAVING_LAYOUT_SUCCESS: "UPDATE_ENGRAVING_LAYOUT_SUCCESS",
  UPDATE_ENGRAVING_LAYOUT_FAILURE: "UPDATE_ENGRAVING_LAYOUT_FAILURE",

  DELETE_ENGRAVING_LAYOUT_REQUEST: "DELETE_ENGRAVING_LAYOUT_REQUEST",
  DELETE_ENGRAVING_LAYOUT_SUCCESS: "DELETE_ENGRAVING_LAYOUT_SUCCESS",
  DELETE_ENGRAVING_LAYOUT_FAILURE: "DELETE_ENGRAVING_LAYOUT_FAILURE",
}
export const engravingCategoryConstants = {
  GET_ENGRAVING_CATEGORY_REQUEST: "GET_ENGRAVING_CATEGORY_REQUEST",
  GET_ENGRAVING_CATEGORY_SUCCESS: "GET_ENGRAVING_CATEGORY_SUCCESS",
  GET_ENGRAVING_CATEGORY_FAILURE: "GET_ENGRAVING_CATEGORY_FAILURE",

  ADD_ENGRAVING_CATEGORY_REQUEST: "ADD_ENGRAVING_CATEGORY_REQUEST",
  ADD_ENGRAVING_CATEGORY_SUCCESS: "ADD_ENGRAVING_CATEGORY_SUCCESS",
  ADD_ENGRAVING_CATEGORY_FAILURE: "ADD_ENGRAVING_CATEGORY_FAILURE",

  UPDATE_ENGRAVING_CATEGORY_REQUEST: "UPDATE_ENGRAVING_CATEGORY_REQUEST",
  UPDATE_ENGRAVING_CATEGORY_SUCCESS: "UPDATE_ENGRAVING_CATEGORY_SUCCESS",
  UPDATE_ENGRAVING_CATEGORY_FAILURE: "UPDATE_ENGRAVING_CATEGORY_FAILURE",

  DELETE_ENGRAVING_CATEGORY_REQUEST: "DELETE_ENGRAVING_CATEGORY_REQUEST",
  DELETE_ENGRAVING_CATEGORY_SUCCESS: "DELETE_ENGRAVING_CATEGORY_SUCCESS",
  DELETE_ENGRAVING_CATEGORY_FAILURE: "DELETE_ENGRAVING_CATEGORY_FAILURE",
}






export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  GET_ALL_USERS_REQUEST: "GET_ALL_USERS_REQUEST",
  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",
};

export const categoryConstansts = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",

  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",

  UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
  UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
  UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",

  DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
  DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
  DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",
};

export const productConstants = {


  GET_PRODUCTS_BY_SLUG_REQUEST: "GET_PRODUCTS_BY_SLUG_REQUEST",
  GET_PRODUCTS_BY_SLUG_SUCCESS: "GET_PRODUCTS_BY_SLUG_SUCCESS",
  GET_PRODUCTS_BY_SLUG_FAILURE: "GET_PRODUCTS_BY_SLUG_FAILURE",

  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

  DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
  DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
  DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  SET_VIEW: "SET_VIEW",
  SET_SORT: "SET_SORT",
  SET_ACTIVE_CATEGORY: "SET_ACTIVE_CATEGORY",


  SEARCH_PRODUCTS_REQUEST: "SEARCH_PRODUCTS_REQUEST",
  SEARCH_PRODUCTS_SUCCESS: "SEARCH_PRODUCTS_SUCCESS",
  SEARCH_PRODUCTS_FAILURE: "SEARCH_PRODUCTS_FAILURE",

  UPDATE_PRODUCT_BY_ID_SUCCESS: "UPDATE_PRODUCT_BY_ID_SUCCESS",
  SET_CURRENT_CATEGORY: "SET_CURRENT_CATEGORY"
};
export const portfolioConstants = {
  GET_ALL_PORTFOLIO_REQUEST: "GET_ALL_PORTFOLIO_REQUEST",
  GET_ALL_PORTFOLIO_SUCCESS: "GET_ALL_PORTFOLIO_SUCCESS",
  GET_ALL_PORTFOLIO_FAILURE: "GET_ALL_PORTFOLIO_FAILURE",

  DELETE_PORTFOLIO_BY_ID_REQUEST: "DELETE_PORTFOLIO_BY_ID_REQUEST",
  DELETE_PORTFOLIO_BY_ID_SUCCESS: "DELETE_PORTFOLIO_BY_ID_SUCCESS",
  DELETE_PORTFOLIO_BY_ID_FAILURE: "DELETE_PORTFOLIO_BY_ID_FAILURE",

  ADD_PORTFOLIO_REQUEST: "ADD_PORTFOLIO_REQUEST",
  ADD_PORTFOLIO_SUCCESS: "ADD_PORTFOLIO_REQUEST",
  ADD_PORTFOLIO_FAILURE: "ADD_PORTFOLIO_FAILURE",
  SET_VIEW: "SET_VIEW",

  SEARCH_PORTFOLIO_REQUEST: "SEARCH_PORTFOLIO_REQUEST",
  SEARCH_PORTFOLIO_SUCCESS: "SEARCH_PORTFOLIO_SUCCESS",
  SEARCH_PORTFOLIO_FAILURE: "SEARCH_PORTFOLIO_FAILURE",

  UPDATE_PORTFOLIO_BY_ID_SUCCESS: "UPDATE_PORTFOLIO_BY_ID_SUCCESS"
};

export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const pageConstants = {
  CREATE_PAGE_REQUEST: "CREATE_PAGE_REQUEST",
  CREATE_PAGE_SUCCESS: "CREATE_PAGE_SUCCESS",
  CREATE_PAGE_FAILURE: "CREATE_PAGE_FAILURE",
};

export const orderConstants = {
  GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
  GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
  GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",

  UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
  UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
  UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
};



export const galleryImageConstants = {
  CREATE_GALLERY_REQUEST: "CREATE_GALLERY_REQUEST",
  CREATE_GALLERY_SUCCESS: "CREATE_GALLERY_SUCCESS",
  CREATE_GALLERY_FAILURE: "CREATE_GALLERY_FAILURE",

  GET_ALL_GALLERY_REQUEST: "GET_ALL_GALLERY_REQUEST",
  GET_ALL_GALLERY_SUCCESS: "GET_ALL_GALLERY_SUCCESS",
  GET_ALL_GALLERY_FAILURE: "GET_ALL_GALLERY_FAILURE",

  DELETE_GALLERY_BY_ID_REQUEST: "DELETE_GALLERY_BY_ID_REQUEST",
  DELETE_GALLERY_BY_ID_SUCCESS: "DELETE_GALLERY_BY_ID_SUCCESS",
  DELETE_GALLERY_BY_ID_FAILURE: "DELETE_GALLERY_BY_ID_FAILURE",
}
export const applicationConstants = {
  GET_ALL_APPLICATION_REQUEST: "GET_ALL_APPLICATION_REQUEST",
  GET_ALL_APPLICATION_SUCCESS: "GET_ALL_APPLICATION_SUCCESS",
  GET_ALL_APPLICATION_FAILURE: "GET_ALL_APPLICATION_FAILURE",
  DELETE_APPLICATION_BY_ID_SUCCESS: "DELETE_APPLICATION_BY_ID_SUCCESS",



}


export const headerConstants = {
  GET_HEADER_REQUEST: "GET_HEADER_REQUEST",
  GET_HEADER_SUCCESS: "GET_HEADER_SUCCESS",
  GET_HEADER_FAILURE: "GET_HEADER_FAILURE",

  ADD_HEADER_REQUEST: "ADD_HEADER_REQUEST",
  ADD_HEADER_SUCCESS: "ADD_HEADER_SUCCESS",
  ADD_HEADER_FAILURE: "ADD_HEADER_FAILURE",

  SET_STATUS_REQUEST: "SET_STATUS_REQUEST",
  SET_STATUS_SUCCESS: "SET_STATUS_SUCCESS",
  SET_STATUS_FAILURE: "SET_STATUS_FAILURE",

  DELETE_HEADER_SUCCESS: "DELETE_HEADER_SUCCESS",

  UPDATE_HEADER_SUCCESS: "UPDATE_HEADER_SUCCESS"
}

export const manufactureConstants = {
  GET_MANUFACTURE_REQUEST: "GET_MANUFACTURE_REQUEST",
  GET_MANUFACTURE_SUCCESS: "GET_MANUFACTURE_SUCCESS",
  GET_MANUFACTURE_FAILURE: "GET_MANUFACTURE_FAILURE",

  ADD_MANUFACTURE_REQUEST: "ADD_MANUFACTURE_REQUEST",
  ADD_MANUFACTURE_SUCCESS: "ADD_MANUFACTURE_SUCCESS",
  ADD_MANUFACTURE_FAILURE: "ADD_MANUFACTURE_FAILURE",

  DELETE_MANUFACTURE_REQUEST: "DELETE_MANUFACTURE_REQUEST",
  DELETE_MANUFACTURE_SUCCESS: "DELETE_MANUFACTURE_SUCCESS",
  DELETE_MANUFACTURE_FAILURE: "DELETE_MANUFACTURE_FAILURE",

  UPDATE_MANUFACTURE_SUCCESS: "UPDATE_MANUFACTURE_SUCCESS"

}


export const promotionConstants = {
  GET_PROMOTION_REQUEST: "GET_PROMOTION_REQUEST",
  GET_PROMOTION_SUCCESS: "GET_PROMOTION_SUCCESS",
  GET_PROMOTION_FAILURE: "GET_PROMOTION_FAILURE",

  ADD_PROMOTION_REQUEST: "ADD_PROMOTION_REQUEST",
  ADD_PROMOTION_SUCCESS: "ADD_PROMOTION_SUCCESS",
  ADD_PROMOTION_FAILURE: "ADD_PROMOTION_FAILURE",

  DELETE_PROMOTION_REQUEST: "DELETE_PROMOTION_REQUEST",
  DELETE_PROMOTION_SUCCESS: "DELETE_PROMOTION_SUCCESS",
  DELETE_PROMOTION_FAILURE: "DELETE_PROMOTION_FAILURE",

  UPDATE_PROMOTION_SUCCESS: "UPDATE_PROMOTION_SUCCESS"
}

export const mainImageConstants = {
  GET_MAIN_IMAGE_REQUEST: "GET_MAIN_IMAGE_REQUEST",
  GET_MAIN_IMAGE_SUCCESS: "GET_MAIN_IMAGE_SUCCESS",
  GET_MAIN_IMAGE_FAILURE: "GET_MAIN_IMAGE_FAILURE",

  ADD_MAIN_IMAGE_REQUEST: "ADD_MAIN_IMAGE_REQUEST",
  ADD_MAIN_IMAGE_SUCCESS: "ADD_MAIN_IMAGE_SUCCESS",
  ADD_MAIN_IMAGE_FAILURE: "ADD_MAIN_IMAGE_FAILURE",

  DELETE_MAIN_IMAGE_REQUEST: "DELETE_MAIN_IMAGE_REQUEST",
  DELETE_MAIN_IMAGE_SUCCESS: "DELETE_MAIN_IMAGE_SUCCESS",
  DELETE_MAIN_IMAGE_FAILURE: "DELETE_MAIN_IMAGE_FAILURE",

  UPDATE_MAIN_IMAGE_REQUEST: "UPDATE_MAIN_IMAGE_REQUEST",
  UPDATE_MAIN_IMAGE_SUCCESS: "UPDATE_MAIN_IMAGE_SUCCESS",
  UPDATE_MAIN_IMAGE_FAILURE: "UPDATE_MAIN_IMAGE_FAILURE",
}

export const comeToUsConstants = {
  GET_COME_TO_US_REQUEST: "GET_COME_TO_US_REQUEST",
  GET_COME_TO_US_SUCCESS: "GET_COME_TO_US_SUCCESS",
  GET_COME_TO_US_FAILURE: "GET_COME_TO_US_FAILURE",

  ADD_COME_TO_US_REQUEST: "ADD_COME_TO_US_REQUEST",
  ADD_COME_TO_US_SUCCESS: "ADD_COME_TO_US_SUCCESS",
  ADD_COME_TO_US_FAILURE: "ADD_COME_TO_US_FAILURE",

  UPDATE_COME_TO_US_REQUEST: "UPDATE_COME_TO_US_REQUEST",
  UPDATE_COME_TO_US_SUCCESS: "UPDATE_COME_TO_US_SUCCESS",
  UPDATE_COME_TO_US_FAILURE: "UPDATE_COME_TO_US_FAILURE",

  DELETE_COME_TO_US_REQUEST: "DELETE_COME_TO_US_REQUEST",
  DELETE_COME_TO_US_SUCCESS: "DELETE_COME_TO_US_SUCCESS",
  DELETE_COME_TO_US_FAILURE: "DELETE_COME_TO_US_FAILURE",
}

export const weWorkOnlineConstants = {
  GET_WE_WORK_ONLINE_REQUEST: "GET_WE_WORK_ONLINE_REQUEST",
  GET_WE_WORK_ONLINE_SUCCESS: "GET_WE_WORK_ONLINE_SUCCESS",
  GET_WE_WORK_ONLINE_FAILURE: "GET_WE_WORK_ONLINE_FAILURE",

  ADD_WE_WORK_ONLINE_REQUEST: "ADD_WE_WORK_ONLINE_REQUEST",
  ADD_WE_WORK_ONLINE_SUCCESS: "ADD_WE_WORK_ONLINE_SUCCESS",
  ADD_WE_WORK_ONLINE_FAILURE: "ADD_WE_WORK_ONLINE_FAILURE",

  UPDATE_WE_WORK_ONLINE_REQUEST: "UPDATE_WE_WORK_ONLINE_REQUEST",
  UPDATE_WE_WORK_ONLINE_SUCCESS: "UPDATE_WE_WORK_ONLINE_SUCCESS",
  UPDATE_WE_WORK_ONLINE_FAILURE: "UPDATE_WE_WORK_ONLINE_FAILURE",

  DELETE_WE_WORK_ONLINE_REQUEST: "DELETE_WE_WORK_ONLINE_REQUEST",
  DELETE_WE_WORK_ONLINE_SUCCESS: "DELETE_WE_WORK_ONLINE_SUCCESS",
  DELETE_WE_WORK_ONLINE_FAILURE: "DELETE_WE_WORK_ONLINE_FAILURE",
}


export const chooseMemorialPhotosConstants = {
  GET_CHOOSE_MEMORIAL_PHOTOS_REQUEST: "GET_CHOOSE_MEMORIAL_PHOTOS_REQUEST",
  GET_CHOOSE_MEMORIAL_PHOTOS_SUCCESS: "GET_CHOOSE_MEMORIAL_PHOTOS_SUCCESS",
  GET_CHOOSE_MEMORIAL_PHOTOS_FAILURE: "GET_CHOOSE_MEMORIAL_PHOTOS_FAILURE",

  ADD_CHOOSE_MEMORIAL_PHOTOS_REQUEST: "ADD_CHOOSE_MEMORIAL_PHOTOS_REQUEST",
  ADD_CHOOSE_MEMORIAL_PHOTOS_SUCCESS: "ADD_CHOOSE_MEMORIAL_PHOTOS_SUCCESS",
  ADD_CHOOSE_MEMORIAL_PHOTOS_FAILURE: "ADD_CHOOSE_MEMORIAL_PHOTOS_FAILURE",

  UPDATE_CHOOSE_MEMORIAL_PHOTOS_REQUEST: "UPDATE_CHOOSE_MEMORIAL_PHOTOS_REQUEST",
  UPDATE_CHOOSE_MEMORIAL_PHOTOS_SUCCESS: "UPDATE_CHOOSE_MEMORIAL_PHOTOS_SUCCESS",
  UPDATE_CHOOSE_MEMORIAL_PHOTOS_FAILURE: "UPDATE_CHOOSE_MEMORIAL_PHOTOS_FAILURE",

  DELETE_CHOOSE_MEMORIAL_PHOTOS_REQUEST: "DELETE_CHOOSE_MEMORIAL_PHOTOS_REQUEST",
  DELETE_CHOOSE_MEMORIAL_PHOTOS_SUCCESS: "DELETE_CHOOSE_MEMORIAL_PHOTOS_SUCCESS",
  DELETE_CHOOSE_MEMORIAL_PHOTOS_FAILURE: "DELETE_CHOOSE_MEMORIAL_PHOTOS_FAILURE",
}

export const engravingConstants = {
  GET_ENGRAVING_REQUEST: "GET_ENGRAVING_REQUEST",
  GET_ENGRAVING_SUCCESS: "GET_ENGRAVING_SUCCESS",
  GET_ENGRAVING_FAILURE: "GET_ENGRAVING_FAILURE",

  ADD_ENGRAVING_REQUEST: "ADD_ENGRAVING_REQUEST",
  ADD_ENGRAVING_SUCCESS: "ADD_ENGRAVING_SUCCESS",
  ADD_ENGRAVING_FAILURE: "ADD_ENGRAVING_FAILURE",

  UPDATE_ENGRAVING_REQUEST: "UPDATE_ENGRAVING_REQUEST",
  UPDATE_ENGRAVING_SUCCESS: "UPDATE_ENGRAVING_SUCCESS",
  UPDATE_ENGRAVING_FAILURE: "UPDATE_ENGRAVING_FAILURE",

  DELETE_ENGRAVING_REQUEST: "DELETE_ENGRAVING_REQUEST",
  DELETE_ENGRAVING_SUCCESS: "DELETE_ENGRAVING_SUCCESS",
  DELETE_ENGRAVING_FAILURE: "DELETE_ENGRAVING_FAILURE",
}

export const contactConstants = {
  GET_CONTACT_REQUEST: "GET_CONTACT_REQUEST",
  GET_CONTACT_SUCCESS: "GET_CONTACT_SUCCESS",
  GET_CONTACT_FAILURE: "GET_CONTACT_FAILURE",

  ADD_CONTACT_REQUEST: "ADD_CONTACT_REQUEST",
  ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",
  ADD_CONTACT_FAILURE: "ADD_CONTACT_FAILURE",

  UPDATE_CONTACT_REQUEST: "UPDATE_CONTACT_REQUEST",
  UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",
  UPDATE_CONTACT_FAILURE: "UPDATE_CONTACT_FAILURE",

  DELETE_CONTACT_REQUEST: "DELETE_CONTACT_REQUEST",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_FAILURE: "DELETE_CONTACT_FAILURE",
}

export const warrantyConstants = {
  GET_WARRANTY_REQUEST: "GET_WARRANTY_REQUEST",
  GET_WARRANTY_SUCCESS: "GET_WARRANTY_SUCCESS",
  GET_WARRANTY_FAILURE: "GET_WARRANTY_FAILURE",

  ADD_WARRANTY_REQUEST: "ADD_WARRANTY_REQUEST",
  ADD_WARRANTY_SUCCESS: "ADD_WARRANTY_SUCCESS",
  ADD_WARRANTY_FAILURE: "ADD_WARRANTY_FAILURE",

  UPDATE_WARRANTY_REQUEST: "UPDATE_WARRANTY_REQUEST",
  UPDATE_WARRANTY_SUCCESS: "UPDATE_WARRANTY_SUCCESS",
  UPDATE_WARRANTY_FAILURE: "UPDATE_WARRANTY_FAILURE",

  DELETE_WARRANTY_REQUEST: "DELETE_WARRANTY_REQUEST",
  DELETE_WARRANTY_SUCCESS: "DELETE_WARRANTY_SUCCESS",
  DELETE_WARRANTY_FAILURE: "DELETE_WARRANTY_FAILURE",
}


export const graniteMaterialConstants = {
  GET_GRANITE_MATERIAL_REQUEST: "GET_GRANITE_MATERIAL_REQUEST",
  GET_GRANITE_MATERIAL_SUCCESS: "GET_GRANITE_MATERIAL_SUCCESS",
  GET_GRANITE_MATERIAL_FAILURE: "GET_GRANITE_MATERIAL_FAILURE",

  ADD_GRANITE_MATERIAL_REQUEST: "ADD_GRANITE_MATERIAL_REQUEST",
  ADD_GRANITE_MATERIAL_SUCCESS: "ADD_GRANITE_MATERIAL_SUCCESS",
  ADD_GRANITE_MATERIAL_FAILURE: "ADD_GRANITE_MATERIAL_FAILURE",

  UPDATE_GRANITE_MATERIAL_REQUEST: "UPDATE_GRANITE_MATERIAL_REQUEST",
  UPDATE_GRANITE_MATERIAL_SUCCESS: "UPDATE_GRANITE_MATERIAL_SUCCESS",
  UPDATE_GRANITE_MATERIAL_FAILURE: "UPDATE_GRANITE_MATERIAL_FAILURE",

  DELETE_GRANITE_MATERIAL_REQUEST: "DELETE_GRANITE_MATERIAL_REQUEST",
  DELETE_GRANITE_MATERIAL_SUCCESS: "DELETE_GRANITE_MATERIAL_SUCCESS",
  DELETE_GRANITE_MATERIAL_FAILURE: "DELETE_GRANITE_MATERIAL_FAILURE",
}

export const paymentListInstructionConstants = {
  GET_PAYMENT_LIST_INSTRUCTION_REQUEST: "GET_PAYMENT_LIST_INSTRUCTION_REQUEST",
  GET_PAYMENT_LIST_INSTRUCTION_SUCCESS: "GET_PAYMENT_LIST_INSTRUCTION_SUCCESS",
  GET_PAYMENT_LIST_INSTRUCTION_FAILURE: "GET_PAYMENT_LIST_INSTRUCTION_FAILURE",

  ADD_PAYMENT_LIST_INSTRUCTION_REQUEST: "ADD_PAYMENT_LIST_INSTRUCTION_REQUEST",
  ADD_PAYMENT_LIST_INSTRUCTION_SUCCESS: "ADD_PAYMENT_LIST_INSTRUCTION_SUCCESS",
  ADD_PAYMENT_LIST_INSTRUCTION_FAILURE: "ADD_PAYMENT_LIST_INSTRUCTION_FAILURE",

  UPDATE_PAYMENT_LIST_INSTRUCTION_REQUEST: "UPDATE_PAYMENT_LIST_INSTRUCTION_REQUEST",
  UPDATE_PAYMENT_LIST_INSTRUCTION_SUCCESS: "UPDATE_PAYMENT_LIST_INSTRUCTION_SUCCESS",
  UPDATE_PAYMENT_LIST_INSTRUCTION_FAILURE: "UPDATE_PAYMENT_LIST_INSTRUCTION_FAILURE",

  DELETE_PAYMENT_LIST_INSTRUCTION_REQUEST: "DELETE_PAYMENT_LIST_INSTRUCTION_REQUEST",
  DELETE_PAYMENT_LIST_INSTRUCTION_SUCCESS: "DELETE_PAYMENT_LIST_INSTRUCTION_SUCCESS",
  DELETE_PAYMENT_LIST_INSTRUCTION_FAILURE: "DELETE_PAYMENT_LIST_INSTRUCTION_FAILURE",
}


export const catalogTitleConstants = {
  GET_CATALOG_TITLE_REQUEST: "GET_CATALOG_TITLE_REQUEST",
  GET_CATALOG_TITLE_SUCCESS: "GET_CATALOG_TITLE_SUCCESS",
  GET_CATALOG_TITLE_FAILURE: "GET_CATALOG_TITLE_FAILURE",

  ADD_CATALOG_TITLE_REQUEST: "ADD_CATALOG_TITLE_REQUEST",
  ADD_CATALOG_TITLE_SUCCESS: "ADD_CATALOG_TITLE_SUCCESS",
  ADD_CATALOG_TITLE_FAILURE: "ADD_CATALOG_TITLE_FAILURE",

  UPDATE_CATALOG_TITLE_REQUEST: "UPDATE_CATALOG_TITLE_REQUEST",
  UPDATE_CATALOG_TITLE_SUCCESS: "UPDATE_CATALOG_TITLE_SUCCESS",
  UPDATE_CATALOG_TITLE_FAILURE: "UPDATE_CATALOG_TITLE_FAILURE",

  DELETE_CATALOG_TITLE_REQUEST: "DELETE_CATALOG_TITLE_REQUEST",
  DELETE_CATALOG_TITLE_SUCCESS: "DELETE_CATALOG_TITLE_SUCCESS",
  DELETE_CATALOG_TITLE_FAILURE: "DELETE_CATALOG_TITLE_FAILURE",
}

export const costDeliveryConstants = {
  GET_COST_DELIVERY_REQUEST: "GET_COST_DELIVERY_REQUEST",
  GET_COST_DELIVERY_SUCCESS: "GET_COST_DELIVERY_SUCCESS",
  GET_COST_DELIVERY_FAILURE: "GET_COST_DELIVERY_FAILURE",

  ADD_COST_DELIVERY_REQUEST: "ADD_COST_DELIVERY_REQUEST",
  ADD_COST_DELIVERY_SUCCESS: "ADD_COST_DELIVERY_SUCCESS",
  ADD_COST_DELIVERY_FAILURE: "ADD_COST_DELIVERY_FAILURE",

  UPDATE_COST_DELIVERY_REQUEST: "UPDATE_COST_DELIVERY_REQUEST",
  UPDATE_COST_DELIVERY_SUCCESS: "UPDATE_COST_DELIVERY_SUCCESS",
  UPDATE_COST_DELIVERY_FAILURE: "UPDATE_COST_DELIVERY_FAILURE",

  DELETE_COST_DELIVERY_REQUEST: "DELETE_COST_DELIVERY_REQUEST",
  DELETE_COST_DELIVERY_SUCCESS: "DELETE_COST_DELIVERY_SUCCESS",
  DELETE_COST_DELIVERY_FAILURE: "DELETE_COST_DELIVERY_FAILURE",
}

export const blogConstants = {
  GET_BLOG_REQUEST: "GET_BLOG_REQUEST",
  GET_BLOG_SUCCESS: "GET_BLOG_SUCCESS",
  GET_BLOG_FAILURE: "GET_BLOG_FAILURE",

  ADD_BLOG_REQUEST: "ADD_BLOG_REQUEST",
  ADD_BLOG_SUCCESS: "ADD_BLOG_SUCCESS",
  ADD_BLOG_FAILURE: "ADD_BLOG_FAILURE",

  UPDATE_BLOG_REQUEST: "UPDATE_BLOG_REQUEST",
  UPDATE_BLOG_SUCCESS: "UPDATE_BLOG_SUCCESS",
  UPDATE_BLOG_FAILURE: "UPDATE_BLOG_FAILURE",

  DELETE_BLOG_REQUEST: "DELETE_BLOG_REQUEST",
  DELETE_BLOG_SUCCESS: "DELETE_BLOG_SUCCESS",
  DELETE_BLOG_FAILURE: "DELETE_BLOG_FAILURE",
  SET_VIEW: "SET_VIEW"
}

export const tombstoneCurbConstants = {
  GET_TOMBSTONE_CURB_REQUEST: "GET_TOMBSTONE_CURB_REQUEST",
  GET_TOMBSTONE_CURB_SUCCESS: "GET_TOMBSTONE_CURB_SUCCESS",
  GET_TOMBSTONE_CURB_FAILURE: "GET_TOMBSTONE_CURB_FAILURE",

  ADD_TOMBSTONE_CURB_REQUEST: "ADD_TOMBSTONE_CURB_REQUEST",
  ADD_TOMBSTONE_CURB_SUCCESS: "ADD_TOMBSTONE_CURB_SUCCESS",
  ADD_TOMBSTONE_CURB_FAILURE: "ADD_TOMBSTONE_CURB_FAILURE",

  UPDATE_TOMBSTONE_CURB_REQUEST: "UPDATE_TOMBSTONE_CURB_REQUEST",
  UPDATE_TOMBSTONE_CURB_SUCCESS: "UPDATE_TOMBSTONE_CURB_SUCCESS",
  UPDATE_TOMBSTONE_CURB_FAILURE: "UPDATE_TOMBSTONE_CURB_FAILURE",

  DELETE_TOMBSTONE_CURB_REQUEST: "DELETE_TOMBSTONE_CURB_REQUEST",
  DELETE_TOMBSTONE_CURB_SUCCESS: "DELETE_TOMBSTONE_CURB_SUCCESS",
  DELETE_TOMBSTONE_CURB_FAILURE: "DELETE_TOMBSTONE_CURB_FAILURE",
  SET_VIEW: "SET_VIEW"
}

export const footerConstants = {
  GET_FOOTER_REQUEST: "GET_FOOTER_REQUEST",
  GET_FOOTER_SUCCESS: "GET_FOOTER_SUCCESS",
  GET_FOOTER_FAILURE: "GET_FOOTER_FAILURE",

  ADD_FOOTER_REQUEST: "ADD_FOOTER_REQUEST",
  ADD_FOOTER_SUCCESS: "ADD_FOOTER_SUCCESS",
  ADD_FOOTER_FAILURE: "ADD_FOOTER_FAILURE",

  UPDATE_FOOTER_REQUEST: "UPDATE_FOOTER_REQUEST",
  UPDATE_FOOTER_SUCCESS: "UPDATE_FOOTER_SUCCESS",
  UPDATE_FOOTER_FAILURE: "UPDATE_FOOTER_FAILURE",

  DELETE_FOOTER_REQUEST: "DELETE_FOOTER_REQUEST",
  DELETE_FOOTER_SUCCESS: "DELETE_FOOTER_SUCCESS",
  DELETE_FOOTER_FAILURE: "DELETE_FOOTER_FAILURE",
}

export const ceramicsConstants = {
  GET_CERAMICS_REQUEST: "GET_CERAMICS_REQUEST",
  GET_CERAMICS_SUCCESS: "GET_CERAMICS_SUCCESS",
  GET_CERAMICS_FAILURE: "GET_CERAMICS_FAILURE",

  ADD_CERAMICS_REQUEST: "ADD_CERAMICS_REQUEST",
  ADD_CERAMICS_SUCCESS: "ADD_CERAMICS_SUCCESS",
  ADD_CERAMICS_FAILURE: "ADD_CERAMICS_FAILURE",

  UPDATE_CERAMICS_REQUEST: "UPDATE_CERAMICS_REQUEST",
  UPDATE_CERAMICS_SUCCESS: "UPDATE_CERAMICS_SUCCESS",
  UPDATE_CERAMICS_FAILURE: "UPDATE_CERAMICS_FAILURE",

  DELETE_CERAMICS_REQUEST: "DELETE_CERAMICS_REQUEST",
  DELETE_CERAMICS_SUCCESS: "DELETE_CERAMICS_SUCCESS",
  DELETE_CERAMICS_FAILURE: "DELETE_CERAMICS_FAILURE",
  SET_VIEW: "SET_VIEW"

}


